services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: meu-backend
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: meu-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
